-- Drop tables in reverse order of dependency
DROP TABLE IF EXISTS file_permissions CASCADE;
DROP TABLE IF EXISTS files CASCADE;
DROP TABLE IF EXISTS appointment_permissions CASCADE;
DROP TABLE IF EXISTS appointment_history CASCADE;
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS remember_me_tokens CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;

-- Create accounts table
CREATE TABLE accounts (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    role VARCHAR(50) DEFAULT 'user' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_login_at TIMESTAMP WITH TIME ZONE,
    ics_token VARCHAR(64)
);

-- Create remember_me_tokens table
CREATE TABLE remember_me_tokens (
    id BIGSERIAL PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    selector VARCHAR(255) UNIQUE NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Create appointments table
CREATE TABLE appointments (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    appointment_date TIMESTAMP NOT NULL,
    created_by BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    notes TEXT,
    icon VARCHAR(50),
    all_day BOOLEAN DEFAULT TRUE NOT NULL,
    duration_hours NUMERIC(5,2) DEFAULT NULL,
    duration_days INT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create appointment_history table
CREATE TABLE appointment_history (
    id BIGSERIAL PRIMARY KEY,
    appointment_id BIGINT NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
    changed_by BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    changes JSONB NOT NULL
);

-- Create appointment_permissions table
CREATE TABLE appointment_permissions (
    appointment_id BIGINT NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
    account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    PRIMARY KEY (appointment_id, account_id)
);

-- Create files table
CREATE TABLE files (
    id BIGSERIAL PRIMARY KEY,
    appointment_id BIGINT REFERENCES appointments(id) ON DELETE SET NULL,
    original_filename VARCHAR(255) NOT NULL,
    storage_filename VARCHAR(255) UNIQUE NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    uploaded_by BIGINT NOT NULL REFERENCES accounts(id),
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create file_permissions table
CREATE TABLE file_permissions (
    file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
    account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    PRIMARY KEY (file_id, account_id)
);

-- Seed accounts: Password is 'Start123!'
-- Hash generated by PHP: $2y$10$nxtyVpSLeSYpXZLtdF7srODa7vDtXgGDan6fzQmmJSfQEWY4VBeum
INSERT INTO accounts (username, password_hash, role, is_active, ics_token) VALUES
('admin_test', '$2y$10$nxtyVpSLeSYpXZLtdF7srODa7vDtXgGDan6fzQmmJSfQEWY4VBeum', 'admin', true, 'ics_token_admin_test_12345'),
('user_a', '$2y$10$nxtyVpSLeSYpXZLtdF7srODa7vDtXgGDan6fzQmmJSfQEWY4VBeum', 'user', true, 'ics_token_user_a_12345'),
('user_b', '$2y$10$nxtyVpSLeSYpXZLtdF7srODa7vDtXgGDan6fzQmmJSfQEWY4VBeum', 'user', true, 'ics_token_user_b_12345');
